### PR TITLE
Cmake integration

### PR DESCRIPTION
**Pull request by zakinadhif**
# Description

Adds CMakeLists.txt and fix compiling issues in GCC and Clang.

# Notable changes

- There's now a macro checking compiler in `Logger.hpp` and `Logger.cpp`
- Changed `std::chrono::high_resolution_clock::now()` to `std::chrono::steady_clock::now()` in `ScopedTimer.hpp`
   Reason of change can be seen in Notes section of https://en.cppreference.com/w/cpp/chrono/high_resolution_clock
   and it also doesn't compile in GCC and Clang.

:)))

### CODE REVIEW

**Review by ThiccTheo — COMMENTED** [review]
noice

**Comment by zakinadhif** [comment]
so are we gonna merge this lol

**Comment by zakinadhif** [comment]
maybe you can test it in your pc first

**Review by ThiccTheo — APPROVED** [review]
nice

**Pull request merged**
